# Verbose log output
verbose: true

# HTTP port
http-port: 8080

# auto open browser for auth
auth-open-browser: true

reddit:
    username: "test"
    request-rate: 5
    max-retry-attempts: 10
    retry-attempt-wait-time: 10
  
spotify:
    client-id: "test1337"
    client-secret: "1337test"

playlists:
    -
        name: "dissic-test"
        subreddits:
            - music
